<a href="https://colab.research.google.com/github/johnsas45/Python-Prep/blob/main/Elarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [26]:
np.array(lista)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr = np.array(lista)
type(arr)


numpy.ndarray

In [28]:
matriz = [1,2,3] , [4,5,6] , [7,8,9]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr[1]

2

In [31]:
arr[0] + arr[5]

7

In [12]:
[13] matriz

SyntaxError: invalid syntax (<ipython-input-12-479ef21a1607>, line 1)

In [32]:
matriz[0]

array([1, 2, 3])

In [33]:
matriz[1]

array([4, 5, 6])

In [15]:
matriz[2]

array([7, 8, 9])

In [16]:
matriz[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [34]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
matriz[0,2]

3

In [35]:
arr [:6]

array([1, 2, 3, 4, 5, 6])

In [36]:
arr [2:]

array([3, 4, 5, 6, 7, 8, 9])

In [37]:
arr [:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr [::3]

array([1, 4, 7])

In [40]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr [-1]

9

In [42]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr [-1]

9

In [44]:
arr [-3:]

array([7, 8, 9])

In [45]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [47]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])